import Footer from "../../components/Footer";
import Navbar from "../../components/Navbar";

export const metadata = {
  title: "PokeNext",
  description: "Generated by create next app",
  "icons": {
    "src": "/images/favicon.ico",
    "sizes": "64x64 32x32 24x24 16x16",
    "type": "image/x-icon"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
